### ISSUE TITLE
Praise for website

### ISSUE THREAD

**Issue by YuvalBernard** [ChenDavidyan/Python_assignments#1]
The cake that you posted on your website looks delicious!
Notice the typo in the hyperlink to the solutions page.

@szabgab

**Comment by ChenDavidyan** [comment]
thanks! I fixed the typo.

**Comment by szabgab** [comment]
Let's see what happens if we paste the link to the relevant commit in the other repo: https://github.com/ChenDavidyan/ChenDavidyan.github.io/commit/6157f3fc8993fd4f4ee62c0820a9b981ed88070e
