### ISSUE TITLE
website comment

### ISSUE THREAD

**Issue by liroh99** [ChenDavidyan/Python_assignments#2]
Hi Chen, 
I think the cake looks amazing, you've got great talent. 
Thanks for tagging me on your webpage :) 
If you'd like, I think you can add some detail as to where you did your bachelor's and your research interests to give a bit of background. 
Good work! 
@szabgab

**Comment by ChenDavidyan** [comment]
Hi Liron, Thank you! I added more information about my bachelor degree which I did at Tel Aviv University.
